### ISSUE TITLE
설치시 에러입니다.

### ISSUE THREAD

**Issue by wanbok** [h2soft/node-gcm#3]
어쩌다 찾게되었는데 창신님꺼라 더반갑네요. 원래는 에러나면 안쓰고말지만 아시는분이라 그냥갈수가 없어서.. ^^;

npm install gcm 후에 에러가 뜹니다. 제 노드 버전에 뭔가 안맞나보네요

아래는 에러메세지 입니다.

npm ERR! Error: No compatible version found: gcm
npm ERR! No valid targets found.
npm ERR! Perhaps not compatible with your version of node?
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:486:10)
npm ERR!     at next_ (/usr/local/lib/node_modules/npm/lib/cache.js:436:17)
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:413:44)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:406:5
npm ERR!     at saved (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:151:7)
npm ERR!     at Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "gcm"
npm ERR! cwd /Users/doubleub/dev/CoffeeScript/easy-bus-server
npm ERR! node -v v0.6.13
npm ERR! npm -v 1.1.15
npm ERR! message No compatible version found: gcm
npm ERR! message No valid targets found.
npm ERR! message Perhaps not compatible with your version of node?
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/doubleub/dev/CoffeeScript/easy-bus-server/npm-debug.log
npm not ok

**Comment by hannesgassert** [comment]
Not a bug. 

This module requires a version of node >= 0.8.0. You're trying with 0.6.13.

**Comment by wanbok** [comment]
Yeah. I was a stupid. :(
Now, I'm using node >= 0.8.0 and it works greatly :)
